<template>
    <svg xml:space="preserve" viewBox="0 0 100 100" y="0" x="0" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1"
        width="200px" height="200px" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g class="ldl-scale"
            style="transform-origin:50% 50%;transform:rotate(0deg) scale(0.8, 0.8);animation-play-state:paused">
            <path stroke="#333" fill="#666766" stroke-miterlimit="10" stroke-width="3.5"
                d="M70.017 58c-13.344 9.178-26.689 9.178-40.033 0-1.755-1.207-2.77-3.233-2.77-5.363v-11.26c0-1.754 1.842-2.926 3.414-2.146 12.915 6.408 25.83 6.408 38.745 0 1.572-.78 3.414.392 3.414 2.146v11.26c-.001 2.131-1.015 4.156-2.77 5.363z"
                style="stroke:rgb(51, 51, 51);fill:rgb(102, 103, 102);animation-play-state:paused"></path>
            <path stroke-miterlimit="10" stroke-width="3.5" stroke="#000" stroke-linejoin="round" opacity=".5"
                d="M69.373 39.231a49.825 49.825 0 0 1-5.873 2.454v7.858c0 4.771-1.014 9.307-2.77 12.011-.39.6-.779 1.179-1.169 1.744 3.485-1.145 6.97-2.9 10.456-5.297 1.755-1.207 2.77-3.233 2.77-5.363v-11.26c-.001-1.755-1.843-2.926-3.414-2.147z"
                style="animation-play-state:paused"></path>
            <path d="M32.333 43.636v9.833" stroke-miterlimit="10" stroke-width="3.5" stroke-linecap="round" stroke="#333"
                fill="none" style="stroke:rgb(51, 51, 51);animation-play-state:paused"></path>
            <path fill="#333"
                d="M85.227 56.694v-4.798a3.988 3.988 0 0 0 2.25-3.581c0-1.578-.922-2.93-2.25-3.581v-8.14h-3.5v8.14a3.987 3.987 0 0 0-2.25 3.581c0 1.578.922 2.93 2.25 3.581v4.798a3.987 3.987 0 0 0-2.25 3.581v18.829h8V60.275c0-1.579-.923-2.93-2.25-3.581z"
                style="fill:rgb(51, 51, 51);animation-play-state:paused"></path>
            <path opacity=".5"
                d="M87.477 48.315c0-1.578-.922-2.93-2.25-3.581v-8.14h-1.75v42.509h4V60.275c0-1.578-.922-2.93-2.25-3.581v-4.798a3.99 3.99 0 0 0 2.25-3.581z"
                style="animation-play-state:paused"></path>
            <path stroke-miterlimit="10" stroke-width="3.5" stroke="#333" fill="#333"
                d="M88.902 37.483L50.605 51.196a1.5 1.5 0 0 1-1.21 0L11.098 37.483c-1.464-.526-1.464-2.221 0-2.747l38.297-13.713a1.5 1.5 0 0 1 1.21 0l38.297 13.713c1.464.527 1.464 2.221 0 2.747z"
                style="stroke:rgb(51, 51, 51);fill:rgb(51, 51, 51);animation-play-state:paused"></path>
            <path stroke-miterlimit="10" stroke-width="3.5" stroke="#000" opacity=".5"
                d="M88.902 34.737l-19.157-6.86c0 .052.005.103.005.155 0 7.433-3.55 14.27-9.492 19.708l28.644-10.256c1.464-.527 1.464-2.221 0-2.747z"
                style="animation-play-state:paused"></path>
            <ellipse fill="#666766" ry="3.485" rx="4.713" cy="33.459" cx="50"
                style="fill:rgb(102, 103, 102);animation-play-state:paused"></ellipse>
            <path opacity=".2"
                d="M50 29.974c-.147 0-.285.022-.429.032 1.2.163 2.142 1.637 2.142 3.453 0 1.816-.943 3.291-2.142 3.453.143.01.282.032.429.032 2.603 0 4.713-1.56 4.713-3.485 0-1.925-2.11-3.485-4.713-3.485z"
                style="animation-play-state:paused"></path>
            <metadata xmlns:d="https://loading.io/stock/" style="animation-play-state:paused">
                <d:name style="animation-play-state:paused">education</d:name>


                <d:tags style="animation-play-state:paused">
                    education,study,learn,research,college,graduate,phd,doctor,teach,instructor,lecturer</d:tags>


                <d:license style="animation-play-state:paused">by</d:license>


                <d:slug style="animation-play-state:paused">fcmayv</d:slug>
            </metadata>
        </g><!-- generated by https://loading.io/ -->
    </svg>
</template>